---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v1.8.2/manifests/install.yaml
  - git-private-repository.yml
  - proxy-service.yml
patchesStrategicMerge:
  - patches/deployment.yml
  - patches/secret.yml
